// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheChampions.Repository;

#nullable disable

namespace TheChampions.Migrations.Payment
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20230617083712_payment")]
    partial class payment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TheChampions.Models.View_Model.PaymentViewModel", b =>
                {
                    b.Property<string>("public_key")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tx_ref")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("public_key");

                    b.ToTable("PaidCustomer");
                });
#pragma warning restore 612, 618
        }
    }
}
